version: "2"

services:
  postgres:
    image: postgres:latest
    container_name: melita_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: melita_db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
    - '5432:5432'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
